name: Trigger CLI Release
on:
  release:
    types: [ published ]
jobs:
  trigger-cli-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Generate App Installation Token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # pin@v1
        with:
          app_id: ${{ secrets.CLI_RELEASE_APP_ID }}
          private_key: ${{ secrets.CLI_RELEASE_PRIVATE_KEY }}
          repository: linode/linode-cli

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@26b39ed245ab8f31526069329e112ab2fb224588 # pin@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: linode/linode-cli
          event-type: cli-release
          client-payload: '{"spec_version": "${{ github.event.release.tag_name }}"}'
